DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(ID INT PRIMARY KEY, STREET VARCHAR(255), HOUSE_NUMBER INT, CITY VARCHAR(255), PC VARCHAR(255));
INSERT INTO Address (ID,STREET,HOUSE_NUMBER,CITY,PC) VALUES (1,'Tuvi','12','Tallinn','10119 ');